on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/maven.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/maven.yml'
    types: [opened, synchronize, reopened]

jobs:
  init-workflow:
    name: init workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{github.event_name}} event."
      - run: echo "This job is now running on a ${{runner.os}} server hosted by giyhub!"
      - run: echo "The name of your branch is ${{github.ref}} and your repository is ${{github.repository}}."

  project-build:
    name: Construct JAR
    runs-on: ubuntu-latest
    needs:
      - init-workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Start MySQL
        run: sudo service mysql start

      - name: Create Database from script
        run: mysql -u${{secrets.DB_USER}} -p${{secrets.DB_PASSWORD}} -e "source springboot-sql.sql"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with: 
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=esaLCuE_tp-api

      - name: Chargins artefact
        uses: actions/upload-artifact@v4
        with:
          name: package.jar
          path: target/*.jar
          retention-days: 1
          
      - run: echo "This job's status is ${{job.status}}."

  docker-build-image-api:
    if: ${{github.ref == 'refs/heah/main'}}
    runs-on: ubuntu-latest
    needs:
      - project-build
    steps:
      - uses: actions/checkout@v4
      - name: SetUpQEMU
        uses: docker/setup-qemu-action@v3
      - name: setUp Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Connect to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: package.jar

      - name: List files in the repository
        run: ls ${{github.workspace}}


      




          
